use_frameworks!

platform :ios, '10.0'

target 'LaTeXMathjaxSwift_Example' do
  pod 'LaTeXMathjaxSwift', :path => '../'

  target 'LaTeXMathjaxSwift_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
