use_frameworks!

platform :ios, '13.0'

target 'LaTeXMathjaxSwift_Example' do
  pod 'LaTeXMathjaxSwift', :path => '../'

  target 'LaTeXMathjaxSwift_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
